### ISSUE TITLE
openSuse Leap 15

### ISSUE THREAD

**Issue by trames57** [rolfn/couchdb2-opensuse#1]
I am getting an error during the ./build-couch-js script.  It is downloading and expanding the SOURCE files in the ~/rpmbuild folder. I am logged in as root. I even tried shutting down apparmor. It seems to be something in the rpmbuild -ba ./js.spec.  I think the git link is not correct. The file it downloaded was js185-1.0.0.tar.gz  which does not match any of the .spec files.

I tried messing around with the git link trying to point to 2.2.0, etc, but there are no .tar.gz files

File /usr/src/packages/SOURCES/js185-1.0.0.tar.gz: No such file or directory

**Comment by rolfn** [comment]
Call this script a normal user not as root.
